### PR TITLE
Fix incorrect hint always sent to Assimp, improved STL reading

### PR DESCRIPTION
**Pull request by davetcoleman**
This greatly improved reading various formats for STL files. Previously the code sent the extension hint as _always_ the entire file name, when it should have sent the extension. Now it does, but falls back to the whole path name.

### CODE REVIEW

**Comment by mikeferguson** [comment]
I haven't tested this -- but out of curiousity -- should we be casting to lowercase? (The solidworks exporter names everything .STL, hence my concern). I'll try to test this shortly.

**Comment by mikeferguson** [comment]
@davetcoleman Can you give an example of a file name that used to fail?

**Comment by davetcoleman** [comment]
> should we be casting to lowercase?

It already does `std::transform(hint.begin(), hint.end(), hint.begin(), ::tolower);`

Example: all files failed. Previously it always passed the entire file name which caused Assimp to fall back to figuring out what type the file was simply by looking at the data. Which it often failed at.

**Comment by davetcoleman** [comment]
We can hold off on this until I do further testing.

**Comment by davetcoleman** [comment]
We used this patch for the APC and it was very critical for getting our meshes to load

**Comment by davetcoleman** [comment]
ping this would be great to have merged in

**Comment by davetcoleman** [comment]
note someone else opened this same fix: https://github.com/ros-planning/geometric_shapes/pull/36

**Comment by v4hn** [comment]
Already made sense to me when I first read this last year.

Merged. Also picked to kinetic-devel

**Comment by davetcoleman** [comment]
Thanks!

**Pull request merged**
