### PR TITLE
[Windows][melodic] Fix shared libraries install path.

### PR DESCRIPTION
**Pull request by seanyen**
Follow http://docs.ros.org/api/catkin/html/howto/format2/building_libraries.html to place shared libraries for better portability.

```cmake
install(TARGETS your_library your_other_library
        ARCHIVE DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
        LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
        RUNTIME DESTINATION ${CATKIN_GLOBAL_BIN_DESTINATION})
```

(Verified in https://aka.ms/ros project.)

### CODE REVIEW

**Comment by seanyen** [comment]
Reopen to trigger travis CI rebuild.

**Review by rhaschke — APPROVED** [review]

**Comment by seanyen** [comment]
@v4hn Hope I am pinging the correct maintainer. This is a simple fix for placing share library for Windows build. Hope you can take a look. Thanks!

**Review by bmagyar — APPROVED** [review]

**Comment by bmagyar** [comment]
@rhaschke please feel free to merge *but* make sure whether this should go into melodic or master.

**Comment by rhaschke** [comment]
@bmagyar Thanks for the 2nd approval.

**Pull request merged**
